### ISSUE TITLE
Planted MagmaPlants disappear

### ISSUE THREAD

**Issue by DelirusCrux** [0TeamDev0/Wild-Mobs#3]
Magmaplants disappear when leaving the area like every other mob. Since you can plant them and farm them, maybe they shouldn't despawn.

**Comment by DracoScythem** [comment]
potential cause is identified - working on a fix

**Comment by DracoScythem** [comment]
fixed in 1.5.2 (https://github.com/0TeamDev0/Wild-Mobs/releases/tag/1.5.2)
