### ISSUE TITLE
Wolves in the twilight forest

### ISSUE THREAD

**Issue by Burgerguys** [0TeamDev0/Wild-Mobs#5]
I have come under the impression that there are some issues with wolves within wild mobs atm. Skeleton wolves that spawn in the overworld, spawn un-interactible and without ai, and will not de spawn. A similar issue to this seems to take place in the twilight forest, where any wolves that spawn will have that same issue. While I have disabled skeleton wolves in the config, I am unsure as to how to mediate the issues within the twilight, and guidance on this subject would be appreciated.

I am playing on version 1.7.10, with the most recently available version of the mod for that mc version as of when I put this modpack together a few weeks ago.

**Comment by V4m4cher0n** [comment]
We are no longer updating or working on this mod, neither do we develop for 1.7.10 anymore, this is a known issue that is not easily fixable. Please update your game.

**Comment by Burgerguys** [comment]
I am playing this specific version of minecraft for the mods that never got updated past this point and thus updating would negate the whole point of I what I am doing, but, thank you for your prompt response.
